# Generated by Django 2.2.7 on 2019-12-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField(blank=True)),
                ('model_id', models.TextField(blank=True)),
                ('cost', models.TextField(blank=True)),
                ('model_url', models.URLField(blank=True)),
            ],
        ),
    ]
