# Generated by Django 2.2.7 on 2019-12-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='model_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
