# Generated by Django 2.2.7 on 2019-12-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191210_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='model_url',
            field=models.URLField(blank=True),
        ),
    ]
