# Generated by Django 2.2.7 on 2019-12-10 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191210_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('student_id', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('dateIn', models.DateField(default=datetime.datetime(2019, 12, 10, 15, 7, 21, 950237))),
                ('dateOut', models.DateTimeField(default=datetime.datetime(2020, 1, 9, 15, 7, 21, 950237))),
                ('laptop', models.ForeignKey(on_delete='CASCADE', to='project.Laptop')),
            ],
        ),
    ]
