# Generated by Django 2.2.7 on 2019-12-10 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateIn',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 15, 49, 50, 843292)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateOut',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 15, 49, 50, 843292)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=datetime.datetime(2019, 12, 10, 15, 49, 50, 843292))),
                ('comment', models.TextField(blank=True)),
                ('laptop', models.ForeignKey(on_delete='CASCADE', to='project.Laptop')),
            ],
        ),
    ]
