# Generated by Django 2.2.7 on 2019-12-10 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20191210_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='person',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateIn',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 15, 56, 21, 950275)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateOut',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 15, 56, 21, 950275)),
        ),
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 15, 56, 21, 950275)),
        ),
    ]
