# Generated by Django 2.2.7 on 2019-12-11 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20191210_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateIn',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 21, 49, 26, 703570)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateOut',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 21, 49, 26, 703570)),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
