# Generated by Django 2.2.7 on 2019-12-11 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20191210_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateIn',
            field=models.DateField(default=datetime.datetime(2019, 12, 11, 10, 17, 5, 547579)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateOut',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 10, 17, 5, 547579)),
        ),
    ]
