# Generated by Django 2.2.7 on 2019-12-11 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20191211_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateIn',
            field=models.DateField(default=datetime.datetime(2019, 12, 11, 11, 50, 52, 290868)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateOut',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 11, 50, 52, 290868)),
        ),
    ]
