# Generated by Django 3.0 on 2019-12-11 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20191211_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateIn',
            field=models.DateField(default=datetime.datetime(2019, 12, 11, 15, 28, 18, 291992)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateOut',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 15, 28, 18, 291992)),
        ),
    ]
