# Generated by Django 3.0 on 2019-12-11 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20191211_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateIn',
            field=models.DateField(default=datetime.datetime(2019, 12, 11, 15, 44, 29, 626602)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateOut',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 15, 44, 29, 626602)),
        ),
    ]
