# Generated by Django 2.2.7 on 2019-11-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0003_auto_20191113_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
